### ISSUE TITLE
Problema na configuração da time zone do mysql

### ISSUE THREAD

**Issue by vieirarester** [vieirarester/SPAM#5]
O valor do fuso horário do servidor 'BRT' não é reconhecido ou representa mais de um fuso horário. Você deve configurar o servidor ou o driver JDBC (através da propriedade de configuração serverTimezone) para usar um valor de fuso horário mais específico se você deseja utilizar o suporte ao fuso horário.
-- Saída @fabriciofx

**Comment by fabriciofx** [comment]
@vieirarester Faltou colocar a exceção:
```
com.mysql.cj.core.exceptions.InvalidConnectionAttributeException: The server time zone
value 'BRT' is unrecognized or represents more than one time zone. You must configure
either the server or JDBC driver (via the serverTimezone configuration property) to use a
more specifc time zone value if you want to utilize time zone support.
```

**Comment by vieirarester** [comment]
A solução incrementada não resolveu o problema. A seguir os passos para reproduzir o erro acima:
1. Abrir página de cadastro de monitores
2. Preencher campos e apertar o botão de cadastro
