### ISSUE TITLE
Problema ao realizar cadastro

### ISSUE THREAD

**Issue by joaowitor21** [vieirarester/SPAM#7]
Quando tentamos realizar o cadastro os atributos que são herdados nas classes Monitor e Aluno da classe Usuario estavam indo nulos para o BD. Eu adicionei uma notação no atributo login da classe Usuario para não aceitar login nulo ou repetido e agora não realiza mais o cadastro devido este problema.
Passo a passo para reproduzir o bug:
 1- Rodar o cadastroAluno;
 2- Preencher os campos e clicar no botão cadastrar;  ##
@fabriciofx @vieirarester

**Comment by fabriciofx** [comment]
@joaowitor21 @vieirarester Acredito que o problema seja porque a classe `Usuario` possui um atributo `login` com a anotação `@Column(nullable = false, unique = true)` e como `Aluno` herda de `Usuario`, ao se construir um objeto `Aluno` ele não está passando o atributo `login` pelo construtor corretamente, sendo necessário este valor.

No mais, ainda acredito que o design das classes de vocês está errado. Um `Aluno` não deveria herdar de `Usuário`. Um `Aluno` ele na verdade possui uma conta de `Usuario`. Assim, a minha recomendação, é que vocês mudem o design das classes e ainda por cima, verifiquem ao construir os objetos, todos os parâmetros estão sendo passados corretamente.
