### ISSUE TITLE
Problema de cadastro de usuários

### ISSUE THREAD

**Issue by vieirarester** [vieirarester/SPAM#8]
O cadastro é feito mas no banco de dados os atributos login e senha nunca são salvos e ficam como null.

A seguir os passos para reproduzir o erro:
1. Executar página de cadastro de aluno ou monitor
2. Preencher dados e clicar no botão Cadastrar

@fabriciofx @vsnepomuceno

**Comment by fabriciofx** [comment]
@vieirarester Aqui, não consegui cadastrar nada. Acredito que o problema já comece pelo que eu descrevi na issue #7.
