### ISSUE TITLE
Problema com inserir publicação

### ISSUE THREAD

**Issue by joaowitor21** [vieirarester/SPAM#9]
Oi, professor. Tudo bem?
Quando eu tento inserir uma publicação aparece alguns erros relacionados a sessão. O senhor poderia dar uma olhada?

Passos para reproduzir o erro:
1- Rodar o index;
2- Cadastrar um aluno;
3- Realizar Login no index;
4- Clicar em Publicar no canto superior;
5- Preencher os dados e apertar em publicar;

Aparece o Seguinte erro:
 javax.faces.FacesException: #{usuarioControlador.inserirPublicacao()}: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: br.edu.ifpe.garanhuns.spam.modelo.negocio.Aluno.usuario.publicacoes, could not initialize proxy - no Session

@fabriciofx @vieirarester

**Comment by vieirarester** [comment]
@vsnepomuceno
